global:
  scrape_interval: 15s

scrape_configs:
- job_name: "control_linux"
  static_configs:
  - targets:
    - 192.168.1.77:9100

- job_name: "worker_nodes_linux"
  static_configs:
  - targets:
    - 192.168.1.90:9100
    - 192.168.1.139:9100

- job_name: "windows"
  static_configs:
  - targets:
    - 192.168.1.51:9182